all:
	g++ -Wl,--add-stdcall-alias -shared -o HelloJNI.dll org_xkit_demo_jni_HelloJNI.cpp  -I"D:/java-jni/curl-7.50.1/include" -I"d:/Program Files/Java/jdk1.8.0_51/include/win32" -I"d:/Program Files/Java/jdk1.8.0_51/include" D:/java-jni/lib/nossl/libcurldll.a
	#gcc -fPIC -shared -o libHelloJNI.so org_xkit_demo_jni_HelloJNI.c -I"/home/mhq/Downloads/jdk1.8.0_65/include/linux" -I"/home/mhq/Downloads/jdk1.8.0_65/include"	
